
openapi: 3.0.0
info:
  title: Spot Trading Hub API
  description: API for managing crypto exchange spot orders
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server
tags:
  - name: Orders
    description: Order management endpoints
paths:
  /orders/cancel:
    post:
      summary: Cancel an order on a specific exchange
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - exchange
                - orderId
                - symbol
              properties:
                exchange:
                  type: string
                  enum: [BINANCE]
                  description: The exchange to cancel the order on
                orderId:
                  type: string
                  description: The ID of the order to cancel
                symbol:
                  type: string
                  description: The trading pair symbol (e.g., BTCUSDT)
      responses:
        200:
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Order 123456 cancelled successfully
                  data:
                    type: object
        400:
          description: Bad request, missing or invalid parameters
        500:
          description: Server error or exchange error
components:
  schemas:
    ExchangeType:
      type: string
      enum: [BINANCE, BYBIT]
      description: Supported exchange types
